In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score
from sklearn.ensemble import RandomForestClassifier

In [2]:
train_df=pd.read_csv("train.csv")
train_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
test_df=pd.read_csv("test.csv")
test_df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [6]:
train_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
test_df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [8]:
train_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

to handle missing values :
-> for coloumns which has so much missing values we will drop this coloumn
->for numerical coloumns that has little missing values we will fill the rest by median because it is robust to outliers and represent the middle age 
->for categorical coloumns that has little missing values we will fill these entries by mode the most repeatable value

In [9]:
train_df["Embarked"].mode()#return series

0    S
Name: Embarked, dtype: object

In [10]:
train_df["Embarked"].mode()[0]

'S'

In [11]:
train_df.drop(columns=['Cabin'], inplace=True)
test_df.drop(columns=['Cabin'], inplace=True)
train_df.drop(columns=["Ticket"],inplace=True)
test_df.drop(columns=["Ticket"],inplace=True)
train_df.drop(columns=["Name"],inplace=True)
test_df.drop(columns=["Name"],inplace=True)
train_df["Age"]=train_df["Age"].fillna(train_df["Age"].median())
test_df["Age"]=test_df["Age"].fillna(test_df["Age"].median())
train_df["Embarked"]=train_df["Embarked"].fillna(train_df["Embarked"].mode()[0])
test_df["Fare"]=test_df["Fare"].fillna(test_df["Fare"].median())

In [12]:
encoder=LabelEncoder()
train_df["Sex"]=encoder.fit_transform(train_df["Sex"])
test_df["Sex"]=encoder.transform(test_df["Sex"])

pd.get_dummies() is a function in pandas that turns categorical values (like text) into numbers — specifically into separate columns that only contain 0s and 1s.
This is called one-hot encoding.

In [13]:
train_df=pd.get_dummies(train_df,columns=["Embarked"],drop_first=True)
test_df=pd.get_dummies(test_df,columns=["Embarked"],drop_first=True)

In [14]:
train_df[["Embarked_Q","Embarked_S"]]=train_df[["Embarked_Q","Embarked_S"]].astype(int)
test_df[["Embarked_Q","Embarked_S"]]=test_df[["Embarked_Q","Embarked_S"]].astype(int)

In [15]:
train_df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S
0,1,0,3,1,22.0,1,0,7.2500,0,1
1,2,1,1,0,38.0,1,0,71.2833,0,0
2,3,1,3,0,26.0,0,0,7.9250,0,1
3,4,1,1,0,35.0,1,0,53.1000,0,1
4,5,0,3,1,35.0,0,0,8.0500,0,1

In [16]:
test_df.head()

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S
0,892,3,1,34.5,0,0,7.8292,1,0
1,893,3,0,47.0,1,0,7.0000,0,1
2,894,2,1,62.0,0,0,9.6875,1,0
3,895,3,1,27.0,0,0,8.6625,0,1
4,896,3,0,22.0,1,1,12.2875,0,1

In [17]:
scalar= MinMaxScaler()
train_df['Age']=scalar.fit_transform(train_df[["Age"]])
test_df["Age"]=scalar.transform(test_df[["Age"]])

In [18]:
train_df['Fare']=scalar.fit_transform(train_df[["Fare"]])
test_df["Fare"]=scalar.transform(test_df[["Fare"]])

In [19]:
x=train_df.drop(columns=["Survived","PassengerId"])
y=train_df["Survived"]

In [20]:
x

     Pclass  Sex       Age  SibSp  Parch      Fare  Embarked_Q  Embarked_S
0         3    1  0.271174      1      0  0.014151           0           1
1         1    0  0.472229      1      0  0.139136           0           0
2         3    0  0.321438      0      0  0.015469           0           1
3         1    0  0.434531      1      0  0.103644           0           1
4         3    1  0.434531      0      0  0.015713           0           1
..      ...  ...       ...    ...    ...       ...         ...         ...
886       2    1  0.334004      0      0  0.025374           0           1
887       1    0  0.233476      0      0  0.058556           0           1
888       3    0  0.346569      1      2  0.045771           0           1
889       1    1  0.321438      0      0  0.058556           0           0
890       3    1  0.396833      0      0  0.015127           1           0

[891 rows x 8 columns]

In [21]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [23]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [26]:
regressor1=LogisticRegression(max_iter=100)
regressor1.fit(x_train,y_train)
y_pred1=regressor1.predict(x_test)

In [27]:
accuracy1=accuracy_score(y_test,y_pred1)
precision1=precision_score(y_test,y_pred1)
recall1=recall_score(y_test,y_pred1)
print(f"the accuracy is {accuracy1}")
print(f"the precision is {precision1}")
print(f"the recall is {recall1}")

the accuracy is 0.7988826815642458
the precision is 0.7714285714285715
the recall is 0.7297297297297297

In [40]:
regressor2=LogisticRegression(max_iter=500)
regressor2.fit(x_train,y_train)
y_pred2=regressor2.predict(x_test)

In [41]:
accuracy2=accuracy_score(y_test,y_pred2)
precision2=precision_score(y_test,y_pred2)
recall2=recall_score(y_test,y_pred2)
print(f"the accuracy is {accuracy2}")
print(f"the precision is {precision2}")
print(f"the recall is {recall2}")

the accuracy is 0.7988826815642458
the precision is 0.7714285714285715
the recall is 0.7297297297297297

In [50]:
tree=DecisionTreeClassifier()
tree.fit(x_train,y_train)
y_pred3=tree.predict(x_test)

In [51]:
accuracy3=accuracy_score(y_test,y_pred3)
precision3=precision_score(y_test,y_pred3)
recall3=recall_score(y_test,y_pred3)
print(f"the accuracy is {accuracy3}")
print(f"the precision is {precision3}")
print(f"the recall is {recall3}")

the accuracy is 0.776536312849162
the precision is 0.7236842105263158
the recall is 0.7432432432432432

In [52]:
forest=RandomForestClassifier(n_estimators=500)
forest.fit(x_train,y_train)
y_pred4=forest.predict(x_test)

In [53]:
accuracy4=accuracy_score(y_test,y_pred4)
precision4=precision_score(y_test,y_pred4)
recall4=recall_score(y_test,y_pred4)
print(f"the accuracy is {accuracy4}")
print(f"the precision is {precision4}")
print(f"the recall is {recall4}")

the accuracy is 0.8268156424581006
the precision is 0.7945205479452054
the recall is 0.7837837837837838

In [56]:
forest2=RandomForestClassifier(n_estimators=1000)
forest2.fit(x_train,y_train)
y_pred5=forest2.predict(x_test)

In [57]:
accuracy5=accuracy_score(y_test,y_pred5)
precision5=precision_score(y_test,y_pred5)
recall5=recall_score(y_test,y_pred5)
print(f"the accuracy is {accuracy5}")
print(f"the precision is {precision5}")
print(f"the recall is {recall5}")

the accuracy is 0.8100558659217877
the precision is 0.7777777777777778
the recall is 0.7567567567567568

In [70]:
forest3=RandomForestClassifier(n_estimators=3000)
forest3.fit(x_train,y_train)
y_pred6=forest3.predict(x_test)

In [71]:
accuracy6=accuracy_score(y_test,y_pred6)
precision6=precision_score(y_test,y_pred6)
recall6=recall_score(y_test,y_pred6)
print(f"the accuracy is {accuracy6}")
print(f"the precision is {precision6}")
print(f"the recall is {recall6}")

the accuracy is 0.8212290502793296
the precision is 0.7916666666666666
the recall is 0.7702702702702703

In [72]:


comparison_df = pd.DataFrame({
    '   Model': ['Logistic Regression with 100 iterations',"logistic regression with 500 iterations", 'Decision Tree', 'Random Forest with 500',"Random Forest with 1000","Random Forest with 3000"],
    '   Accuracy': [accuracy1, accuracy2, accuracy3,accuracy4,accuracy5,accuracy6],
    '   Precision': [precision1, precision2, precision3,precision4,precision5,precision6],
    '   Recall': [recall1, recall2, recall3,recall4,recall5,recall6],
})

print(comparison_df)

                                     Model  Accuracy  Precision    Recall
0  Logistic Regression with 100 iterations  0.798883   0.771429  0.729730
1  logistic regression with 500 iterations  0.798883   0.771429  0.729730
2                            Decision Tree  0.776536   0.723684  0.743243
3                   Random Forest with 500  0.826816   0.794521  0.783784
4                  Random Forest with 1000  0.810056   0.777778  0.756757
5                  Random Forest with 3000  0.821229   0.791667  0.770270

we deduce that Random Forest with 500 is optimal one

In [73]:
x_testsub=test_df.drop(columns=["PassengerId"])

In [74]:
x_testsub

     Pclass  Sex       Age  SibSp  Parch      Fare  Embarked_Q  Embarked_S
0         3    1  0.428248      0      0  0.015282           1           0
1         3    0  0.585323      1      0  0.013663           0           1
2         2    1  0.773813      0      0  0.018909           1           0
3         3    1  0.334004      0      0  0.016908           0           1
4         3    0  0.271174      1      1  0.023984           0           1
..      ...  ...       ...    ...    ...       ...         ...         ...
413       3    1  0.334004      0      0  0.015713           0           1
414       1    0  0.484795      0      0  0.212559           0           0
415       3    1  0.478512      0      0  0.014151           0           1
416       3    1  0.334004      0      0  0.015713           0           1
417       3    1  0.334004      1      1  0.043640           0           0

[418 rows x 8 columns]

In [75]:
forest=RandomForestClassifier(n_estimators=500)
forest.fit(x_train,y_train)
y_submission=forest.predict(x_testsub)
y_submission

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0])

In [76]:
submission = pd.DataFrame({
    'PassengerId': test_df['PassengerId'],
    'Survived': y_submission
})

In [77]:
submission.to_csv("submission.csv", index=False)